channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=22.0.2
- pip:
  - mlflow==2.9.2
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - packaging==23.2
  - pandas==2.3.1
  - pyarrow==14.0.2
  - pyyaml==6.0.2
  - scikit-learn==1.7.1
  - scipy==1.15.3
name: mlflow-env
